baseURL: https://senvang.org/
languageCode: en-us
title: senvang.org
theme: terminal

params:
  themeColor: blue
  centerTheme: true

languages:
  en:
    languageName: English
    title: senvang.org
    subtitle:

    params:
      logo:
        logoText: SENVANG IT Solutions | Stefan Römer
        logoHomeLink: /

    menu:
      main:
      - identifier: business
        name: business
        url: /business
        weight: 1
      - identifier: about
        name: about me
        url: /about
        weight: 2
      - identifier: contact
        name: contact
        url: /contact
        weight: 3
      - identifier: posts
        name: posts
        url: /posts
        weight: 4
